/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { OpeningWeekDayService } from "../openingWeekDay.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Public } from "../../decorators/public.decorator";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { OpeningWeekDayCreateInput } from "./OpeningWeekDayCreateInput";
import { OpeningWeekDayWhereInput } from "./OpeningWeekDayWhereInput";
import { OpeningWeekDayWhereUniqueInput } from "./OpeningWeekDayWhereUniqueInput";
import { OpeningWeekDayFindManyArgs } from "./OpeningWeekDayFindManyArgs";
import { OpeningWeekDayUpdateInput } from "./OpeningWeekDayUpdateInput";
import { OpeningWeekDay } from "./OpeningWeekDay";
import { OpenHourFindManyArgs } from "../../openHour/base/OpenHourFindManyArgs";
import { OpenHour } from "../../openHour/base/OpenHour";
import { OpenHourWhereUniqueInput } from "../../openHour/base/OpenHourWhereUniqueInput";
@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class OpeningWeekDayControllerBase {
  constructor(
    protected readonly service: OpeningWeekDayService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "OpeningWeekDay",
    action: "create",
    possession: "any",
  })
  @common.Post()
  @swagger.ApiCreatedResponse({ type: OpeningWeekDay })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async create(
    @common.Body() data: OpeningWeekDayCreateInput
  ): Promise<OpeningWeekDay> {
    return await this.service.create({
      data: {
        ...data,

        store: data.store
          ? {
              connect: data.store,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,

        store: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        weekday: true,
      },
    });
  }

  @Public()
  @common.Get()
  @swagger.ApiOkResponse({ type: [OpeningWeekDay] })
  @swagger.ApiForbiddenResponse()
  @ApiNestedQuery(OpeningWeekDayFindManyArgs)
  async findMany(@common.Req() request: Request): Promise<OpeningWeekDay[]> {
    const args = plainToClass(OpeningWeekDayFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,
        id: true,

        store: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        weekday: true,
      },
    });
  }

  @Public()
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: OpeningWeekDay })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async findOne(
    @common.Param() params: OpeningWeekDayWhereUniqueInput
  ): Promise<OpeningWeekDay | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,
        id: true,

        store: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        weekday: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @nestAccessControl.UseRoles({
    resource: "OpeningWeekDay",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: OpeningWeekDay })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async update(
    @common.Param() params: OpeningWeekDayWhereUniqueInput,
    @common.Body() data: OpeningWeekDayUpdateInput
  ): Promise<OpeningWeekDay | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          store: data.store
            ? {
                connect: data.store,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,

          store: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          weekday: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @nestAccessControl.UseRoles({
    resource: "OpeningWeekDay",
    action: "delete",
    possession: "any",
  })
  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: OpeningWeekDay })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @swagger.ApiForbiddenResponse({ type: errors.ForbiddenException })
  async delete(
    @common.Param() params: OpeningWeekDayWhereUniqueInput
  ): Promise<OpeningWeekDay | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,
          id: true,

          store: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
          weekday: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @nestAccessControl.UseRoles({
    resource: "OpenHour",
    action: "read",
    possession: "any",
  })
  @common.Get("/:id/openHour")
  @ApiNestedQuery(OpenHourFindManyArgs)
  async findManyOpenHour(
    @common.Req() request: Request,
    @common.Param() params: OpeningWeekDayWhereUniqueInput
  ): Promise<OpenHour[]> {
    const query = plainToClass(OpenHourFindManyArgs, request.query);
    const results = await this.service.findOpenHour(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        openingWeekDays: {
          select: {
            id: true,
          },
        },

        startTime: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @nestAccessControl.UseRoles({
    resource: "OpeningWeekDay",
    action: "update",
    possession: "any",
  })
  @common.Post("/:id/openHour")
  async connectOpenHour(
    @common.Param() params: OpeningWeekDayWhereUniqueInput,
    @common.Body() body: OpenHourWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      openHour: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "OpeningWeekDay",
    action: "update",
    possession: "any",
  })
  @common.Patch("/:id/openHour")
  async updateOpenHour(
    @common.Param() params: OpeningWeekDayWhereUniqueInput,
    @common.Body() body: OpenHourWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      openHour: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @nestAccessControl.UseRoles({
    resource: "OpeningWeekDay",
    action: "update",
    possession: "any",
  })
  @common.Delete("/:id/openHour")
  async disconnectOpenHour(
    @common.Param() params: OpeningWeekDayWhereUniqueInput,
    @common.Body() body: OpenHourWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      openHour: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
