version: "3"
services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
      ports: ${DB_POSTGRES_PORT}:5432
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - ${DB_POSTGRES_PORT}:${DB_POSTGRES_PORT}
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${DB_MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${DB_MONGO_PASSWORD}
      ME_CONFIG_MONGODB_PORT: ${DB_MONGO_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_MONGO_USER_ADMIN}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_MONGO_PASSWORD_ADMIN}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_MONGO_USER_ADMIN}:${DB_MONGO_PASSWORD_ADMIN}@mongodb:27017/
    links:
      - mongodb
    networks:
      - mongo-compose-network
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_MONGO_USER_ADMIN}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_MONGO_PASSWORD_ADMIN}
    ports:
      - "${DB_MONGO_PORT}:27017"
    volumes:
      - "mongo:/data/db"
    networks:
      - mongo-compose-network

networks:
  mongo-compose-network:
    driver: bridge
volumes:
  postgres: ~
  mongo: ~
